### YamlMime:OData
uid: Microsoft.Dynamics.CRM.msdyn_configuration
name: "msdyn_configuration"
type: entitytype
metadata: 
  title: "Microsoft Dynamics 365 Customer Engagement msdyn_configuration EntityType Reference | MicrosoftDocs"
  ms.date: "03/20/2018"
  ms.service: "crm-online"
  ms.topic: "reference"
  applies_to: 
  - "Dynamics 365 (online)"
  ms.assetid: 03f15e7e-a4aa-410d-9d6f-62472577e2f8
  author: "jimdaly"
  ms.author: "jdaly"
  manager: "jdaly"
  meta-description: "Reference information about the Dynamics 365 Customer Engagement msdyn_configuration entitytype."
description: "This entity is used to store queries and templates."
header:
  entity_set_path: "[organization URI]/api/data/v9.0/msdyn_configurations"
  base_type: Microsoft.Dynamics.CRM.crmbaseentity
  display_name: Configuration
  primary_key: msdyn_configurationid
  primary_name_attribute: msdyn_name
  operations_supported:
  - POST
  - GET
  - PATCH
  - DELETE
namespace: Microsoft.Dynamics.CRM
properties:
  description: "Properties represent fields of data stored in the entity.Some properties are read-only."
  property_items:
    - name: createdon
      type: Edm.DateTimeOffset
      display_name: "Created On"
      description: "Date and time when the record was created."
      iscomputed: false
      isreadonly: true
    - name: importsequencenumber
      type: Edm.Int32
      display_name: "Import Sequence Number"
      description: "Sequence number of the import that created this record."
      iscomputed: false
      isreadonly: false
    - name: modifiedon
      type: Edm.DateTimeOffset
      display_name: "Modified On"
      description: "Date and time when the record was modified."
      iscomputed: false
      isreadonly: true
    - name: msdyn_configurationid
      type: Edm.Guid
      display_name: "Configuration"
      description: "Unique identifier for entity instances"
      iscomputed: false
      isreadonly: false
    - name: msdyn_name
      type: Edm.String
      display_name: "Name"
      description: "The name of the custom entity."
      iscomputed: false
      isreadonly: false
    - name: msdyn_type
      type: Edm.Int32
      display_name: "Type"
      description: ""
      iscomputed: false
      isreadonly: false
      options:
        - value: 192350000
          label: "Filter Layout"
        - value: 192350001
          label: "Resource Cell Template"
        - value: 192350002
          label: "Retrieve Resources Query"
        - value: 192350003
          label: "Schedule Assistant Filter Layout"
        - value: 192350004
          label: "Schedule Assistant Retrieve Constraints Query"
        - value: 192350005
          label: "Clone Entity Query"
    - name: msdyn_value
      type: Edm.String
      display_name: ""
      description: "To store queries and templates."
      iscomputed: false
      isreadonly: false
    - name: overriddencreatedon
      type: Edm.DateTimeOffset
      display_name: "Record Created On"
      description: "Date and time that the record was migrated."
      iscomputed: false
      isreadonly: false
    - name: statecode
      type: Edm.Int32
      display_name: "Status"
      description: "Status of the Configuration"
      iscomputed: false
      isreadonly: false
      options:
        - value: 0
          label: "Active"
        - value: 1
          label: "Inactive"
    - name: statuscode
      type: Edm.Int32
      display_name: "Status Reason"
      description: "Reason for the status of the Configuration"
      iscomputed: false
      isreadonly: false
      options:
        - value: 1
          label: "Active"
        - value: 2
          label: "Inactive"
    - name: timezoneruleversionnumber
      type: Edm.Int32
      display_name: "Time Zone Rule Version Number"
      description: "For internal use only."
      iscomputed: false
      isreadonly: false
    - name: utcconversiontimezonecode
      type: Edm.Int32
      display_name: "UTC Conversion Time Zone Code"
      description: "Time zone code that was in use when the record was created."
      iscomputed: false
      isreadonly: false
    - name: versionnumber
      type: Edm.Int64
      display_name: "Version Number"
      description: "Version Number"
      iscomputed: false
      isreadonly: true
lookup_properties:
  description: "Lookup properties are read-only, computed properties which contain entity primary key Edm.Guid data for one or more corresponding single-valued navigation properties. More information: [Lookup properties](https://docs.microsoft.com/dynamics365/customer-engagement/developer/webapi/web-api-types-operations#lookup-properties) and [Retrieve data about lookup properties](https://docs.microsoft.com/dynamics365/customer-engagement/developer/webapi/query-data-web-api#retrieve-data-about-lookup-properties)."
  property_items:
  - name: _createdby_value
    single_valued_navigation_property:
    - createdby
    description: "Unique identifier of the user who created the record."
  - name: _createdonbehalfby_value
    single_valued_navigation_property:
    - createdonbehalfby
    description: "Unique identifier of the delegate user who created the record."
  - name: _modifiedby_value
    single_valued_navigation_property:
    - modifiedby
    description: "Unique identifier of the user who modified the record."
  - name: _modifiedonbehalfby_value
    single_valued_navigation_property:
    - modifiedonbehalfby
    description: "Unique identifier of the delegate user who modified the record."
  - name: _ownerid_value
    single_valued_navigation_property:
    - ownerid
    description: "Owner Id"
  - name: _owningbusinessunit_value
    single_valued_navigation_property:
    - owningbusinessunit
    description: "Unique identifier for the business unit that owns the record"
  - name: _owningteam_value
    single_valued_navigation_property:
    - owningteam
    description: "Unique identifier for the team that owns the record."
  - name: _owninguser_value
    single_valued_navigation_property:
    - owninguser
    description: "Unique identifier for the user that owns the record."
single_valued_navigation_properties:
  description: "Single-valued navigation properties represent lookup fields where a single entity can be referenced. Each single-valued navigation property has a corresponding partner collection-valued navigation property on the related entity."
  property_items:
  - name: createdby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_msdyn_configuration_createdby
  - name: createdonbehalfby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_msdyn_configuration_createdonbehalfby
  - name: modifiedby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_msdyn_configuration_modifiedby
  - name: modifiedonbehalfby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_msdyn_configuration_modifiedonbehalfby
  - name: ownerid
    type: Microsoft.Dynamics.CRM.principal
    partner: owner_msdyn_configuration
  - name: owningbusinessunit
    type: Microsoft.Dynamics.CRM.businessunit
    partner: business_unit_msdyn_configuration
  - name: owningteam
    type: Microsoft.Dynamics.CRM.team
    partner: team_msdyn_configuration
  - name: owninguser
    type: Microsoft.Dynamics.CRM.systemuser
    partner: user_msdyn_configuration
collection_valued_navigation_properties:
  description: "Collection-valued navigation properties represent collections of entities which may represent either a one-to-many (1:N) or many-to-many (N:N) relationship between the entities."
  property_items:
  - name: msdyn_configuration_AsyncOperations
    type: Microsoft.Dynamics.CRM.asyncoperation
    partner: regardingobjectid_msdyn_configuration
  - name: msdyn_configuration_BulkDeleteFailures
    type: Microsoft.Dynamics.CRM.bulkdeletefailure
    partner: regardingobjectid_msdyn_configuration
  - name: msdyn_configuration_MailboxTrackingFolders
    type: Microsoft.Dynamics.CRM.mailboxtrackingfolder
    partner: regardingobjectid_msdyn_configuration
  - name: msdyn_configuration_PrincipalObjectAttributeAccesses
    type: Microsoft.Dynamics.CRM.principalobjectattributeaccess
    partner: objectid_msdyn_configuration
  - name: msdyn_configuration_ProcessSession
    type: Microsoft.Dynamics.CRM.processsession
    partner: regardingobjectid_msdyn_configuration
  - name: msdyn_configuration_SyncErrors
    type: Microsoft.Dynamics.CRM.syncerror
    partner: regardingobjectid_msdyn_configuration
  - name: msdyn_msdyn_configuration_msdyn_bookingsetupmetadata_CloneEntityQuery
    type: Microsoft.Dynamics.CRM.msdyn_bookingsetupmetadata
    partner: msdyn_CloneEntityQuery
  - name: msdyn_msdyn_configuration_msdyn_bookingsetupmetadata_RetrieveConstraintsQuery
    type: Microsoft.Dynamics.CRM.msdyn_bookingsetupmetadata
    partner: msdyn_RetrieveConstraintsQuery
  - name: msdyn_msdyn_configuration_msdyn_bookingsetupmetadata_RetrieveResourcesQuery
    type: Microsoft.Dynamics.CRM.msdyn_bookingsetupmetadata
    partner: msdyn_RetrieveResourcesQuery
  - name: msdyn_msdyn_configuration_msdyn_scheduleboardsetting_FilterLayout
    type: Microsoft.Dynamics.CRM.msdyn_scheduleboardsetting
    partner: msdyn_FilterLayout
  - name: msdyn_msdyn_configuration_msdyn_scheduleboardsetting_ResourceCellTemplate
    type: Microsoft.Dynamics.CRM.msdyn_scheduleboardsetting
    partner: msdyn_ResourceCellTemplate
  - name: msdyn_msdyn_configuration_msdyn_scheduleboardsetting_RetrieveResourcesQuery
    type: Microsoft.Dynamics.CRM.msdyn_scheduleboardsetting
    partner: msdyn_RetrieveResourcesQuery
# This entity has no derived entities.
operations:
  description: "The following operations can be used with the msdyn_configuration entity type."
  operation_items:
  - name: Microsoft.Dynamics.CRM.GrantAccess
    binding_type: "Not Bound"
  - name: Microsoft.Dynamics.CRM.IsValidStateTransition
    binding_type: "Not Bound"
  - name: Microsoft.Dynamics.CRM.ModifyAccess
    binding_type: "Not Bound"
  - name: Microsoft.Dynamics.CRM.RetrievePrincipalAccess
    binding_type: "Not Bound"
  - name: Microsoft.Dynamics.CRM.RetrieveSharedPrincipalsAndAccess
    binding_type: "Not Bound"
  - name: Microsoft.Dynamics.CRM.RevokeAccess
    binding_type: "Not Bound"
solutions:
  description: "The following solutions include the msdyn_configuration entity type."
  solution_items:
  - type: Microsoft.Dynamics.CRM.MicrosoftDynamicsScheduling
    description: "Unified scheduling solution provides the infrastructure to express resource requirements for any entity in the system and help staff those requirements with resources based on the availability and applicability of the resource for the requirement."
# This entity has no remarks.
href_see_also:
- text: "Use the Microsoft Dynamics 365 Customer Engagement Web API"
  href: "https://docs.microsoft.com/dynamics365/customer-engagement/developer/use-microsoft-dynamics-365-web-api"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex