### YamlMime:OData
uid: Microsoft.Dynamics.CRM.msdyn_postruleconfig
name: "msdyn_postruleconfig"
type: entitytype
metadata: 
  title: "Microsoft Dynamics 365 Customer Engagement msdyn_postruleconfig EntityType Reference | MicrosoftDocs"
  ms.date: "03/20/2018"
  ms.service: "crm-online"
  ms.topic: "reference"
  applies_to: 
  - "Dynamics 365 (online)"
  ms.assetid: f2d9e3ee-c07e-4d01-9298-f0a97958b3e3
  author: "jimdaly"
  ms.author: "jdaly"
  manager: "jdaly"
  meta-description: "Reference information about the Dynamics 365 Customer Engagement msdyn_postruleconfig entitytype."
description: "Enable or disable system post rules for an entity for Activity Feeds and Yammer."
header:
  entity_set_path: "[organization URI]/api/data/v9.0/msdyn_postruleconfigs"
  base_type: Microsoft.Dynamics.CRM.crmbaseentity
  display_name: Post Rule Configuration
  primary_key: msdyn_postruleconfigid
  primary_name_attribute: msdyn_name
  operations_supported:
  - POST
  - GET
  - PATCH
  - DELETE
namespace: Microsoft.Dynamics.CRM
properties:
  description: "Properties represent fields of data stored in the entity.Some properties are read-only."
  property_items:
    - name: createdon
      type: Edm.DateTimeOffset
      display_name: "Created On"
      description: "Date and time when the record was created."
      iscomputed: false
      isreadonly: true
    - name: importsequencenumber
      type: Edm.Int32
      display_name: "Import Sequence Number"
      description: "Sequence number of the import that created this record."
      iscomputed: false
      isreadonly: false
    - name: modifiedon
      type: Edm.DateTimeOffset
      display_name: "Modified On"
      description: "Date and time when the record was modified."
      iscomputed: false
      isreadonly: true
    - name: msdyn_formatid
      type: Edm.String
      display_name: "Format ID"
      description: "Internal Use Only."
      iscomputed: false
      isreadonly: false
    - name: msdyn_name
      type: Edm.String
      display_name: "Name"
      description: "Name of the rule."
      iscomputed: false
      isreadonly: false
    - name: msdyn_postruleconfigid
      type: Edm.Guid
      display_name: "Post Rule Configuration Id"
      description: "Unique identifier of the post rule configuration."
      iscomputed: false
      isreadonly: false
    - name: msdyn_posttoyammer
      type: Edm.Boolean
      display_name: "Post to Yammer Activity Stream"
      description: "Determine whether to post this message to the Yammer Activity Stream. Please do not check this box if this message contains sensitive information requiring Microsoft Dynamics 365 access."
      iscomputed: false
      isreadonly: false
      options:
        - value: 1
          label: "Yes"
        - value: 0
          label: "No"
    - name: msdyn_ruleid
      type: Edm.String
      display_name: "Rule ID"
      description: "Identifier in the format WebResourceName:SchemaName of the definition for this rule."
      iscomputed: false
      isreadonly: false
    - name: msdyn_rulesource
      type: Edm.String
      display_name: "Rule Source"
      description: "Internal Use Only."
      iscomputed: false
      isreadonly: false
    - name: msdyn_stepid
      type: Edm.String
      display_name: "Step ID"
      description: "Unique identifier of the SDK message processing step for this rule."
      iscomputed: false
      isreadonly: false
    - name: overriddencreatedon
      type: Edm.DateTimeOffset
      display_name: "Record Created On"
      description: "Date and time that the record was migrated."
      iscomputed: false
      isreadonly: false
    - name: statecode
      type: Edm.Int32
      display_name: "Status"
      description: "Status of the Post Rule Configuration"
      iscomputed: false
      isreadonly: false
      options:
        - value: 0
          label: "Active"
        - value: 1
          label: "Inactive"
    - name: statuscode
      type: Edm.Int32
      display_name: "Status Reason"
      description: "Reason for the status of the Post Rule Configuration"
      iscomputed: false
      isreadonly: false
      options:
        - value: 1
          label: "Active"
        - value: 2
          label: "Inactive"
    - name: timezoneruleversionnumber
      type: Edm.Int32
      display_name: "Time Zone Rule Version Number"
      description: "For internal use only."
      iscomputed: false
      isreadonly: false
    - name: utcconversiontimezonecode
      type: Edm.Int32
      display_name: "UTC Conversion Time Zone Code"
      description: "Time zone code that was in use when the record was created."
      iscomputed: false
      isreadonly: false
    - name: versionnumber
      type: Edm.Int64
      display_name: "Version Number"
      description: "Version Number"
      iscomputed: false
      isreadonly: true
lookup_properties:
  description: "Lookup properties are read-only, computed properties which contain entity primary key Edm.Guid data for one or more corresponding single-valued navigation properties. More information: [Lookup properties](https://docs.microsoft.com/dynamics365/customer-engagement/developer/webapi/web-api-types-operations#lookup-properties) and [Retrieve data about lookup properties](https://docs.microsoft.com/dynamics365/customer-engagement/developer/webapi/query-data-web-api#retrieve-data-about-lookup-properties)."
  property_items:
  - name: _createdby_value
    single_valued_navigation_property:
    - createdby
    description: "Unique identifier of the user who created the record."
  - name: _createdonbehalfby_value
    single_valued_navigation_property:
    - createdonbehalfby
    description: "Unique identifier of the delegate user who created the record."
  - name: _modifiedby_value
    single_valued_navigation_property:
    - modifiedby
    description: "Unique identifier of the user who modified the record."
  - name: _modifiedonbehalfby_value
    single_valued_navigation_property:
    - modifiedonbehalfby
    description: "Unique identifier of the delegate user who modified the record."
  - name: _msdyn_postconfigid_value
    single_valued_navigation_property:
    - msdyn_PostConfigId
    description: "Entity that is enabled for Activity feeds."
  - name: _organizationid_value
    single_valued_navigation_property:
    - organizationid
    description: "Unique identifier for the organization"
single_valued_navigation_properties:
  description: "Single-valued navigation properties represent lookup fields where a single entity can be referenced. Each single-valued navigation property has a corresponding partner collection-valued navigation property on the related entity."
  property_items:
  - name: createdby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_msdyn_postruleconfig_createdby
  - name: createdonbehalfby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_msdyn_postruleconfig_createdonbehalfby
  - name: modifiedby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_msdyn_postruleconfig_modifiedby
  - name: modifiedonbehalfby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_msdyn_postruleconfig_modifiedonbehalfby
  - name: msdyn_PostConfigId
    type: Microsoft.Dynamics.CRM.msdyn_postconfig
    partner: msdyn_postconfig_msdyn_postruleconfig
  - name: organizationid
    type: Microsoft.Dynamics.CRM.organization
    partner: organization_msdyn_postruleconfig
collection_valued_navigation_properties:
  description: "Collection-valued navigation properties represent collections of entities which may represent either a one-to-many (1:N) or many-to-many (N:N) relationship between the entities."
  property_items:
  - name: msdyn_postruleconfig_AsyncOperations
    type: Microsoft.Dynamics.CRM.asyncoperation
    partner: regardingobjectid_msdyn_postruleconfig
  - name: msdyn_postruleconfig_BulkDeleteFailures
    type: Microsoft.Dynamics.CRM.bulkdeletefailure
    partner: regardingobjectid_msdyn_postruleconfig
  - name: msdyn_postruleconfig_MailboxTrackingFolders
    type: Microsoft.Dynamics.CRM.mailboxtrackingfolder
    partner: regardingobjectid_msdyn_postruleconfig
  - name: msdyn_postruleconfig_PrincipalObjectAttributeAccesses
    type: Microsoft.Dynamics.CRM.principalobjectattributeaccess
    partner: objectid_msdyn_postruleconfig
  - name: msdyn_postruleconfig_ProcessSession
    type: Microsoft.Dynamics.CRM.processsession
    partner: regardingobjectid_msdyn_postruleconfig
  - name: msdyn_postruleconfig_SyncErrors
    type: Microsoft.Dynamics.CRM.syncerror
    partner: regardingobjectid_msdyn_postruleconfig
# This entity has no derived entities.
operations:
  description: "The following operations can be used with the msdyn_postruleconfig entity type."
  operation_items:
  - name: Microsoft.Dynamics.CRM.IsValidStateTransition
    binding_type: "Not Bound"
solutions:
  description: "The following solutions include the msdyn_postruleconfig entity type."
  solution_items:
  - type: Microsoft.Dynamics.CRM.ActivityFeedsCore
    description: "This solution enables Activity Feeds including Walls for your Microsoft Dynamics 365 organization."
  - type: Microsoft.Dynamics.CRM.ProjectService
    description: "Microsoft Dynamics 365 for Project Service Automation is an end-to-end solution that helps sales and delivery teams engage customers and deliver billable projects on time and within budget. Project Service gives you the tools you need to: Estimate, quote, and contract work; Plan and assign resources; Enable team collaboration; Capture time, expense, and progress data for real-time insights and accurate invoicing."
# This entity has no remarks.
href_see_also:
- text: "Use the Microsoft Dynamics 365 Customer Engagement Web API"
  href: "https://docs.microsoft.com/dynamics365/customer-engagement/developer/use-microsoft-dynamics-365-web-api"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex