### YamlMime:OData
uid: Microsoft.Dynamics.CRM.productassociation
name: "productassociation"
type: entitytype
metadata: 
  title: "Microsoft Dynamics 365 Customer Engagement productassociation EntityType Reference | MicrosoftDocs"
  ms.date: "03/20/2018"
  ms.service: "crm-online"
  ms.topic: "reference"
  applies_to: 
  - "Dynamics 365 (online)"
  ms.assetid: 29302c07-c782-4f59-81e5-61317c01cbfd
  author: "jimdaly"
  ms.author: "jdaly"
  manager: "jdaly"
  meta-description: "Reference information about the Dynamics 365 Customer Engagement productassociation entitytype."
description: "Instance of a product added to a bundle or kit."
header:
  entity_set_path: "[organization URI]/api/data/v9.0/productassociations"
  base_type: Microsoft.Dynamics.CRM.crmbaseentity
  display_name: Product Association
  primary_key: productassociationid
  primary_name_attribute: productidname
  operations_supported:
  - POST
  - GET
  - PATCH
  - DELETE
namespace: Microsoft.Dynamics.CRM
properties:
  description: "Properties represent fields of data stored in the entity.Some properties are read-only."
  property_items:
    - name: createdon
      type: Edm.DateTimeOffset
      display_name: "Created On"
      description: "Date and time when the record was created."
      iscomputed: false
      isreadonly: true
    - name: dmtimportstate
      type: Edm.Int32
      display_name: "Internal Use Only"
      description: "Internal Use Only"
      iscomputed: false
      isreadonly: false
    - name: exchangerate
      type: Edm.Decimal
      display_name: "Exchange Rate"
      description: "Shows the conversion rate of the record's currency. The exchange rate is used to convert all money fields in the record from the local currency to the system's default currency."
      iscomputed: false
      isreadonly: true
    - name: importsequencenumber
      type: Edm.Int32
      display_name: "Import Sequence Number"
      description: "Sequence number of the import that created this record."
      iscomputed: false
      isreadonly: false
    - name: modifiedon
      type: Edm.DateTimeOffset
      display_name: "Modified On"
      description: "Date and time when the record was modified."
      iscomputed: false
      isreadonly: true
    - name: overriddencreatedon
      type: Edm.DateTimeOffset
      display_name: "Record Created On"
      description: "Date and time that the record was migrated."
      iscomputed: false
      isreadonly: false
    - name: productassociationid
      type: Edm.Guid
      display_name: "Product Association ID"
      description: "Shows the unique identifier of the product association."
      iscomputed: false
      isreadonly: false
    - name: productisrequired
      type: Edm.Int32
      display_name: "Required"
      description: "Select whether the associated product is required or optional."
      iscomputed: false
      isreadonly: false
      options:
        - value: 0
          label: "Optional"
        - value: 1
          label: "Required"
    - name: propertycustomizationstatus
      type: Edm.Int32
      display_name: "Property Customization"
      description: "Shows whether the item has properties that can be customized."
      iscomputed: false
      isreadonly: false
      options:
        - value: 0
          label: "Not Available"
        - value: 1
          label: "Available"
    - name: quantity
      type: Edm.Decimal
      display_name: "Quantity"
      description: "Type the quantity of the products added to the bundle or kit."
      iscomputed: false
      isreadonly: false
    - name: statecode
      type: Edm.Int32
      display_name: "Status"
      description: "Shows whether the associated product is active or inactive."
      iscomputed: false
      isreadonly: false
      options:
        - value: 0
          label: "Active"
        - value: 1
          label: "Inactive"
        - value: 2
          label: "Draft"
        - value: 3
          label: "Under Revision"
    - name: statuscode
      type: Edm.Int32
      display_name: "Status Reason"
      description: "Select the associated product's status."
      iscomputed: false
      isreadonly: false
      options:
        - value: 1
          label: "Active"
        - value: 2
          label: "Inactive"
        - value: 0
          label: "Draft"
        - value: 3
          label: "DraftActive"
    - name: timezoneruleversionnumber
      type: Edm.Int32
      display_name: "Time Zone Rule Version Number"
      description: "For internal use only."
      iscomputed: false
      isreadonly: false
    - name: utcconversiontimezonecode
      type: Edm.Int32
      display_name: "UTC Conversion Time Zone Code"
      description: "Time zone code that was in use when the record was created."
      iscomputed: false
      isreadonly: false
    - name: versionnumber
      type: Edm.Int64
      display_name: "Version Number"
      description: "Version Number"
      iscomputed: false
      isreadonly: true
lookup_properties:
  description: "Lookup properties are read-only, computed properties which contain entity primary key Edm.Guid data for one or more corresponding single-valued navigation properties. More information: [Lookup properties](https://docs.microsoft.com/dynamics365/customer-engagement/developer/webapi/web-api-types-operations#lookup-properties) and [Retrieve data about lookup properties](https://docs.microsoft.com/dynamics365/customer-engagement/developer/webapi/query-data-web-api#retrieve-data-about-lookup-properties)."
  property_items:
  - name: _associatedproduct_value
    single_valued_navigation_property:
    - associatedproduct
    description: "Select a product to add to the bundle or kit."
  - name: _createdby_value
    single_valued_navigation_property:
    - createdby
    description: "Shows who created the record."
  - name: _createdonbehalfby_value
    single_valued_navigation_property:
    - createdonbehalfby
    description: "Shows who created the record on behalf of another user."
  - name: _modifiedby_value
    single_valued_navigation_property:
    - modifiedby
    description: "Shows who last updated the record."
  - name: _modifiedonbehalfby_value
    single_valued_navigation_property:
    - modifiedonbehalfby
    description: "Shows who created the record on behalf of another user."
  - name: _organizationid_value
    single_valued_navigation_property:
    - organizationid
    description: "Unique identifier for the organization"
  - name: _productid_value
    single_valued_navigation_property:
    - productid
    description: "Select a bundle or a kit."
  - name: _transactioncurrencyid_value
    single_valued_navigation_property:
    - transactioncurrencyid
    description: "Shows the currency associated with the record."
  - name: _uomid_value
    single_valued_navigation_property:
    - uomid
    description: "Shows the unit of the product association."
single_valued_navigation_properties:
  description: "Single-valued navigation properties represent lookup fields where a single entity can be referenced. Each single-valued navigation property has a corresponding partner collection-valued navigation property on the related entity."
  property_items:
  - name: associatedproduct
    type: Microsoft.Dynamics.CRM.product
    partner: Product_ProductAssociation_AssocProd
  - name: createdby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_ProductAssociate_createdby
  - name: createdonbehalfby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_ProductAssociation_createdonbehalfby
  - name: modifiedby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_ProductAssociation_modifiedby
  - name: modifiedonbehalfby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_ProductAssociation_modifiedonbehalfby
  - name: organizationid
    type: Microsoft.Dynamics.CRM.organization
    partner: organization_ProductAssociation
  - name: productid
    type: Microsoft.Dynamics.CRM.product
    partner: Product_ProductAssociation_Prod
  - name: transactioncurrencyid
    type: Microsoft.Dynamics.CRM.transactioncurrency
    partner: transactioncurrency_ProductAssociation
  - name: uomid
    type: Microsoft.Dynamics.CRM.uom
    partner: unit_of_measurement_productassociation
collection_valued_navigation_properties:
  description: "Collection-valued navigation properties represent collections of entities which may represent either a one-to-many (1:N) or many-to-many (N:N) relationship between the entities."
  property_items:
  - name: ProductAssociation_AsyncOperations
    type: Microsoft.Dynamics.CRM.asyncoperation
    partner: regardingobjectid_productassociation
  - name: productassociation_BulkDeleteFailures
    type: Microsoft.Dynamics.CRM.bulkdeletefailure
    partner: regardingobjectid_productassociation
  - name: ProductAssociation_DynamicProperty
    type: Microsoft.Dynamics.CRM.dynamicproperty
    partner: regardingobjectid_productassociation
  - name: ProductAssociation_DynamicPropertyAssociation
    type: Microsoft.Dynamics.CRM.dynamicpropertyassociation
    partner: regardingobjectid_productassociation
  - name: productAssociation_invoice_details
    type: Microsoft.Dynamics.CRM.invoicedetail
    partner: productassociationid_productassociation
  - name: productassociation_MailboxTrackingFolders
    type: Microsoft.Dynamics.CRM.mailboxtrackingfolder
    partner: regardingobjectid_productassociation
  - name: productAssociation_opportunity_product
    type: Microsoft.Dynamics.CRM.opportunityproduct
    partner: productassociationid_productassociation
  - name: ProductAssociation_PrincipalObjectAttributeAccess
    type: Microsoft.Dynamics.CRM.principalobjectattributeaccess
    partner: objectid_productassociation
  - name: ProductAssociation_ProcessSessions
    type: Microsoft.Dynamics.CRM.processsession
    partner: regardingobjectid_productassociation
  - name: productAssociation_quote_details
    type: Microsoft.Dynamics.CRM.quotedetail
    partner: productassociationid_productassociation
  - name: productAssociation_salesorder_details
    type: Microsoft.Dynamics.CRM.salesorderdetail
    partner: productassociationid_productassociation
  - name: ProductAssociation_SyncErrors
    type: Microsoft.Dynamics.CRM.syncerror
    partner: regardingobjectid_productassociation_syncerror
# This entity has no derived entities.
# This entity has no operations
solutions:
  description: "The following solutions include the productassociation entity type."
  solution_items:
  - type: Microsoft.Dynamics.CRM.msdynce_ProductManagement
    description: "Dynamics 365 workload for product management."
# This entity has no remarks.
href_see_also:
- text: "Use the Microsoft Dynamics 365 Customer Engagement Web API"
  href: "https://docs.microsoft.com/dynamics365/customer-engagement/developer/use-microsoft-dynamics-365-web-api"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex