### YamlMime:OData
uid: Microsoft.Dynamics.CRM.productsalesliterature
name: "productsalesliterature"
type: entitytype
metadata: 
  title: "Microsoft Dynamics 365 Customer Engagement productsalesliterature EntityType Reference | MicrosoftDocs"
  ms.date: "03/20/2018"
  ms.service: "crm-online"
  ms.topic: "reference"
  applies_to: 
  - "Dynamics 365 (online)"
  ms.assetid: 6c77765f-c61b-442a-a6c9-c2539ce9cc7c
  author: "jimdaly"
  ms.author: "jdaly"
  manager: "jdaly"
  meta-description: "Reference information about the Dynamics 365 Customer Engagement productsalesliterature entitytype."
# This entity doesn't have a description
header:
  entity_set_path: "[organization URI]/api/data/v9.0/productsalesliteratures"
  base_type: Microsoft.Dynamics.CRM.crmbaseentity
  display_name: ProductSalesLiterature
  primary_key: productsalesliteratureid
  primary_name_attribute: name
  operations_supported:
  - GET (RetrieveMultiple Only)
namespace: Microsoft.Dynamics.CRM
properties:
  description: "Properties represent fields of data stored in the entity.Some properties are read-only."
  property_items:
    - name: importsequencenumber
      type: Edm.Int32
      display_name: "Import Sequence Number"
      description: "Sequence number of the import that created this record."
      iscomputed: false
      isreadonly: false
    - name: name
      type: Edm.String
      display_name: "name"
      description: "name"
      iscomputed: false
      isreadonly: false
    - name: overriddencreatedon
      type: Edm.DateTimeOffset
      display_name: "Record Created On"
      description: "Date and time that the record was migrated."
      iscomputed: false
      isreadonly: false
    - name: productid
      type: Edm.Guid
      display_name: ""
      description: ""
      iscomputed: false
      isreadonly: true
    - name: productsalesliteratureid
      type: Edm.Guid
      display_name: ""
      description: "Unique identifier of the product sales literature associated with this price list."
      iscomputed: false
      isreadonly: false
    - name: salesliteratureid
      type: Edm.Guid
      display_name: ""
      description: ""
      iscomputed: false
      isreadonly: true
    - name: timezoneruleversionnumber
      type: Edm.Int32
      display_name: "Time Zone Rule Version Number"
      description: "For internal use only."
      iscomputed: false
      isreadonly: false
    - name: utcconversiontimezonecode
      type: Edm.Int32
      display_name: "UTC Conversion Time Zone Code"
      description: "Time zone code that was in use when the record was created."
      iscomputed: false
      isreadonly: false
    - name: versionnumber
      type: Edm.Int64
      display_name: "Version Number"
      description: "Version Number"
      iscomputed: false
      isreadonly: true
# This entity has no lookup properties
# This entity has no single-valued navigation properties
collection_valued_navigation_properties:
  description: "Collection-valued navigation properties represent collections of entities which may represent either a one-to-many (1:N) or many-to-many (N:N) relationship between the entities."
  property_items:
  - name: productsalesliterature_AsyncOperations
    type: Microsoft.Dynamics.CRM.asyncoperation
    partner: regardingobjectid_productsalesliterature
  - name: productsalesliterature_BulkDeleteFailures
    type: Microsoft.Dynamics.CRM.bulkdeletefailure
    partner: regardingobjectid_productsalesliterature
  - name: productsalesliterature_MailboxTrackingFolders
    type: Microsoft.Dynamics.CRM.mailboxtrackingfolder
    partner: regardingobjectid_productsalesliterature
  - name: productsalesliterature_PrincipalObjectAttributeAccesses
    type: Microsoft.Dynamics.CRM.principalobjectattributeaccess
    partner: objectid_productsalesliterature
# This entity has no derived entities.
# This entity has no operations
solutions:
  description: "The following solutions include the productsalesliterature entity type."
  solution_items:
  - type: Microsoft.Dynamics.CRM.msdynce_Sales
    description: "Dynamics 365 workload for sales."
# This entity has no remarks.
href_see_also:
- text: "Use the Microsoft Dynamics 365 Customer Engagement Web API"
  href: "https://docs.microsoft.com/dynamics365/customer-engagement/developer/use-microsoft-dynamics-365-web-api"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex