### YamlMime:OData
uid: Microsoft.Dynamics.CRM.sdkmessageprocessingstepsecureconfig
name: "sdkmessageprocessingstepsecureconfig"
type: entitytype
metadata: 
  title: "Microsoft Dynamics 365 Customer Engagement sdkmessageprocessingstepsecureconfig EntityType Reference | MicrosoftDocs"
  ms.date: "03/20/2018"
  ms.service: "crm-online"
  ms.topic: "reference"
  applies_to: 
  - "Dynamics 365 (online)"
  ms.assetid: 7de01abe-56b3-44b3-b2c8-8408025a7230
  author: "jimdaly"
  ms.author: "jdaly"
  manager: "jdaly"
  meta-description: "Reference information about the Dynamics 365 Customer Engagement sdkmessageprocessingstepsecureconfig entitytype."
description: "Non-public custom configuration that is passed to a plug-in's constructor."
header:
  entity_set_path: "[organization URI]/api/data/v9.0/sdkmessageprocessingstepsecureconfigs"
  base_type: Microsoft.Dynamics.CRM.crmbaseentity
  display_name: Sdk Message Processing Step Secure Configuration
  primary_key: sdkmessageprocessingstepsecureconfigid
  # This entity doesn't have a primaryAttributeName
  operations_supported:
  - POST
  - GET
  - PATCH
  - DELETE
namespace: Microsoft.Dynamics.CRM
properties:
  description: "Properties represent fields of data stored in the entity.Some properties are read-only."
  property_items:
    - name: createdon
      type: Edm.DateTimeOffset
      display_name: "Created On"
      description: "Date and time when the SDK message processing step was created."
      iscomputed: false
      isreadonly: true
    - name: customizationlevel
      type: Edm.Int32
      display_name: ""
      description: "Customization level of the SDK message processing step secure configuration."
      iscomputed: false
      isreadonly: true
    - name: modifiedon
      type: Edm.DateTimeOffset
      display_name: "Modified On"
      description: "Date and time when the SDK message processing step was last modified."
      iscomputed: false
      isreadonly: true
    - name: sdkmessageprocessingstepsecureconfigid
      type: Edm.Guid
      display_name: ""
      description: "Unique identifier of the SDK message processing step secure configuration."
      iscomputed: false
      isreadonly: false
    - name: sdkmessageprocessingstepsecureconfigidunique
      type: Edm.Guid
      display_name: ""
      description: "Unique identifier of the SDK message processing step."
      iscomputed: false
      isreadonly: true
    - name: secureconfig
      type: Edm.String
      display_name: "Secure Configuration"
      description: "Secure step-specific configuration for the plug-in type that is passed to the plug-in's constructor at run time."
      iscomputed: false
      isreadonly: false
lookup_properties:
  description: "Lookup properties are read-only, computed properties which contain entity primary key Edm.Guid data for one or more corresponding single-valued navigation properties. More information: [Lookup properties](https://docs.microsoft.com/dynamics365/customer-engagement/developer/webapi/web-api-types-operations#lookup-properties) and [Retrieve data about lookup properties](https://docs.microsoft.com/dynamics365/customer-engagement/developer/webapi/query-data-web-api#retrieve-data-about-lookup-properties)."
  property_items:
  - name: _createdby_value
    single_valued_navigation_property:
    - createdby
    description: "Unique identifier of the user who created the SDK message processing step."
  - name: _createdonbehalfby_value
    single_valued_navigation_property:
    - createdonbehalfby
    description: "Unique identifier of the delegate user who created the sdkmessageprocessingstepsecureconfig."
  - name: _modifiedby_value
    single_valued_navigation_property:
    - modifiedby
    description: "Unique identifier of the user who last modified the SDK message processing step."
  - name: _modifiedonbehalfby_value
    single_valued_navigation_property:
    - modifiedonbehalfby
    description: "Unique identifier of the delegate user who last modified the sdkmessageprocessingstepsecureconfig."
  - name: _organizationid_value
    single_valued_navigation_property:
    - organizationid
    description: "Unique identifier of the organization with which the SDK message processing step is associated."
single_valued_navigation_properties:
  description: "Single-valued navigation properties represent lookup fields where a single entity can be referenced. Each single-valued navigation property has a corresponding partner collection-valued navigation property on the related entity."
  property_items:
  - name: createdby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: createdby_sdkmessageprocessingstepsecureconfig
  - name: createdonbehalfby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_sdkmessageprocessingstepsecureconfig_createdonbehalfby
  - name: modifiedby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: modifiedby_sdkmessageprocessingstepsecureconfig
  - name: modifiedonbehalfby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_sdkmessageprocessingstepsecureconfig_modifiedonbehalfby
  - name: organizationid
    type: Microsoft.Dynamics.CRM.organization
    partner: organization_sdkmessageprocessingstepsecureconfig
collection_valued_navigation_properties:
  description: "Collection-valued navigation properties represent collections of entities which may represent either a one-to-many (1:N) or many-to-many (N:N) relationship between the entities."
  property_items:
  - name: sdkmessageprocessingstepsecureconfigid_sdkmessageprocessingstep
    type: Microsoft.Dynamics.CRM.sdkmessageprocessingstep
    partner: sdkmessageprocessingstepsecureconfigid
# This entity has no derived entities.
# This entity has no operations
solutions:
  description: "The following solutions include the sdkmessageprocessingstepsecureconfig entity type."
  solution_items:
  - type: Microsoft.Dynamics.CRM.System
    description: "Internal CRM System Solution"
# This entity has no remarks.
href_see_also:
- text: "Use the Microsoft Dynamics 365 Customer Engagement Web API"
  href: "https://docs.microsoft.com/dynamics365/customer-engagement/developer/use-microsoft-dynamics-365-web-api"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex