### YamlMime:OData
uid: Microsoft.Dynamics.CRM.UpdateFeatureConfig
name: "UpdateFeatureConfig"
type: action
metadata: 
  title: "Microsoft Dynamics 365 Customer Engagement UpdateFeatureConfig Action Reference | MicrosoftDocs"
  ms.date: "03/20/2018"
  ms.service: "crm-online"
  ms.topic: "reference"
  applies_to: 
  - "Dynamics 365 (online)"
  ms.assetid: c4901254-7f28-4dcf-96e9-ed6adfb606c7
  author: "jimdaly"
  ms.author: "jdaly"
  manager: "jdaly"
  meta-description: "Reference information about the Dynamics 365 Customer Engagement UpdateFeatureConfig Action."
namespace: Microsoft.Dynamics.CRM
description: "internal"
owningsolution: Microsoft.Dynamics.CRM.System
# This action has no bound entities.
isbound: false
parameters:
  description: "Parameters allow for data to be passed to the action."
  parameter_items:
  - name: FeatureType
    type: Edm.Int32
    nullable: false
    unicode: true
    description: "internal"
  - name: ConfigData
    type: Edm.String
    nullable: false
    unicode: false
    description: "internal"
# This action has no return value.
hasreturnvalue: false
# This action has no identified unbound entities.
# This action has no remarks.
href_see_also:
- text: "Use the Microsoft Dynamics 365 Customer Engagement Web API"
  href: "https://docs.microsoft.com/dynamics365/customer-engagement/developer/use-microsoft-dynamics-365-web-api"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex