### YamlMime:OData
uid: Microsoft.Dynamics.CRM.RetrieveApplicationRibbon
name: "RetrieveApplicationRibbon"
type: function
metadata: 
  title: "Microsoft Dynamics 365 Customer Engagement RetrieveApplicationRibbon Function Reference | MicrosoftDocs"
  ms.date: "03/20/2018"
  ms.service: "crm-online"
  ms.topic: "reference"
  applies_to: 
  - "Dynamics 365 (online)"
  ms.assetid: 329b188c-e953-4017-93dc-441bd395facf
  author: "jimdaly"
  ms.author: "jdaly"
  manager: "jdaly"
  meta-description: "Reference information about the Dynamics 365 Customer Engagement RetrieveApplicationRibbon Function."
namespace: Microsoft.Dynamics.CRM
description: "Retrieve the data that defines the content and behavior of the application ribbon.  "
iscomposable: false
# This function is not bound to any entities.
isbound: false
# This function has no parameters.
hasparameters: false
return_type:
  description: "The RetrieveApplicationRibbon function returns the following value."
  type: Microsoft.Dynamics.CRM.RetrieveApplicationRibbonResponse
  iscollection: false
  nullable: false
# This function no specific entities for this function identified.
# This function has no remarks.
href_see_also:
- text: "Use the Microsoft Dynamics 365 Customer Engagement Web API"
  href: "https://docs.microsoft.com/dynamics365/customer-engagement/developer/use-microsoft-dynamics-365-web-api"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex